In [20]:
# This is needed for DataFrameMapper
%pip install sklearn-pandas

Note: you may need to restart the kernel to use updated packages.


In [1]:
# Load necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

# For SVM stuff
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import WhitespaceTokenizer
from sklearn.preprocessing import LabelEncoder, StandardScaler, OrdinalEncoder
from sklearn_pandas import DataFrameMapper
from gensim.models.doc2vec import Doc2Vec

Format does basic work to change the format of columns into something we can use.

In [2]:
def format_df(df):
    df["deadline"] = pd.to_datetime(df["deadline"])
    df["launched"] = pd.to_datetime(df["launched"])
    df["success"] = df["pledged"] >= df["goal"]
    df["duration"] = df["deadline"] - df["launched"]
    return df

Clean removes columns we don't care about. Namely:
* When the duration is less than one day
* If the project state is 'live'
* If the project state is cancelled

In [3]:
# Taken from Michael's notebook
def clean_df(df):
    df = df.drop(df.loc[df["duration"] < datetime.timedelta(days=1)].index)
    df = df.drop(df.loc[df["state"] == "live"].index)
    df = df.drop(df.loc[df["state"] == "canceled"].index)
    return df

These functions define the transformations of the columns we care about into the forms we're interested in running actual algorithms on. 

In [4]:
def tokenize(text): 
    tknzr = WhitespaceTokenizer()
    return tknzr.tokenize(text)

# TODO: use an embedding instead??
def get_count_vectorizer():
    nltk.download('stopwords')
    en_stopwords = set(stopwords.words("english")) 
    count_vectorizer = CountVectorizer(stop_words=en_stopwords, analyzer='word', tokenizer=tokenize, min_df=1)
    return count_vectorizer

def get_main_category_encoder():
    main_category_le = LabelEncoder()
    main_category_le.fit(train_clean['main_category'])
    return main_category_le

def get_category_encoder():
    category_le = LabelEncoder()
    category_le.fit(train_clean['category'])
    return category_le

def build_doc2vec(names, embedding_length=20):
    tokenized = names.apply(tokenize)
    tokenized = list(tokenized)
    
    # this is fairly important, having a corpus_file instead of in-memory data
    # speeds up building the model significantly
    # https://github.com/RaRe-Technologies/gensim/issues/2218
    with open("data/train_names.txt", "w") as f:
        for doc in tokenized:
            f.write(" ".join(doc) + "\n")
    
    # https://radimrehurek.com/gensim/models/doc2vec.html
    # note that infer_vector is NOT deterministic
    # https://github.com/RaRe-Technologies/gensim/issues/447
    # and they shouldn't be forced to be determinstic
    model = Doc2Vec(corpus_file="data/train_names.txt", vector_size=20, min_count=1, workers=7)
    return model
    
# expects a series of names
def doc2vec_names(names, model):
    tokenized = names.apply(tokenize)
    tokenized = list(tokenized)
    
    vectorized = [model.infer_vector(doc) for doc in tokenized]
    return vectorized

def get_mapper():
    main_category_le = get_main_category_encoder()
    category_le = get_category_encoder()
    count_vectorizer = get_count_vectorizer()

    mapper = DataFrameMapper([
        ('name', count_vectorizer),
        ('main_category', main_category_le),
        ('category', category_le),
        (['duration'], StandardScaler()),
        (['usd_goal_real'], StandardScaler()),
        (['launched_month', 'deadline_month'], OrdinalEncoder()),
    ], df_out=True)
    return mapper

def transform_df(df, mapper, fit=False):
    X = df[["name", "main_category", "category", "duration", "usd_goal_real"]].copy()
    X["launched_month"] = df["launched"].apply(lambda x: x.month)
    X["deadline_month"] = df["deadline"].apply(lambda x: x.month)
    X["duration"] = X["duration"].apply(lambda x: x.seconds)
    
    if fit:
        X_mapped = mapper.fit_transform(X)
    else:
        X_mapped = mapper.transform(X)
        
    y = df["success"].copy()
    
    return X_mapped, y, mapper
    

In [5]:
# Taken from Michael's notebook
train_full = pd.read_csv("data/2018-train.csv").dropna()
validate_full = pd.read_csv("data/2018-validate.csv").dropna()

In [6]:
# Taken from Michael's notebook
train_format = format_df(train_full)
validate_format = format_df(validate_full)

In [7]:
# Taken from Michael's notebook
train_clean = clean_df(train_format)
valid_clean = clean_df(validate_format)
train_clean.head()

Unnamed: 0          ID                                               name  \
0      319122   695425648  Peace-building through story-making with youth...   
2      175494   189251239                     Colored Baggies for Boardgames   
4      141771  1720248225  Two Scoops of Beauty health wellness women eve...   
5      236644   272982453                 Gavarcia - Haute Couture in Canada   
6      231360   245912004  "One Last Crazy F*cking Night" (#OLCFN) The Movie   

           category main_category currency   deadline     goal  \
0  Children's Books    Publishing      SEK 2015-06-09   6000.0   
2    Tabletop Games         Games      USD 2013-01-07   6000.0   
4            Events          Food      USD 2016-09-04   5202.0   
5           Couture       Fashion      CAD 2015-04-16   3000.0   
6    Narrative Film  Film & Video      USD 2013-03-01  50000.0   

             launched  pledged       state  backers country  usd pledged  \
0 2015-05-10 14:53:53   6251.0  successful       15      SE       756.92   
2 2012-11-08 20:06:31  15151.0  successful      518      US     15151.00   
4 2016-08-05 01:26:56      0.0      failed        0      US         0.00   
5 2015-03-18 16:27:44    556.0      failed        8      CA       434.86   
6 2013-01-30 17:55:02   3041.0      failed       28      US      3041.00   

   usd_pledged_real  usd_goal_real  success         duration  
0            762.02         731.42     True 29 days 09:06:07  
2          15151.00        6000.00     True 59 days 03:53:29  
4              0.00        5202.00    False 29 days 22:33:04  
5            456.07        2460.83    False 28 days 07:32:16  
6           3041.00       50000.00    False 29 days 06:04:58

In [8]:
%%time
# example doc2vec usage
model = build_doc2vec(train_clean["name"])

CPU times: user 3min 44s, sys: 49.3 s, total: 4min 34s
Wall time: 2min 26s


In [9]:
%%time
vectorized_names = doc2vec_names(train_clean["name"], model)

CPU times: user 3min 9s, sys: 0 ns, total: 3min 9s
Wall time: 3min 9s


In [10]:
vectorized_names[:5]

[array([ 0.04361228, -0.02603678,  0.04302235, -0.01056258, -0.02098303,
        -0.01242309, -0.05192544,  0.0046178 ,  0.01002172, -0.00840567,
         0.05564684, -0.09543984, -0.01014506,  0.02251204,  0.03464296,
        -0.01593683,  0.00240719,  0.02585901, -0.07216214,  0.03373416],
       dtype=float32),
 array([-0.06794597, -0.01340604,  0.01937855, -0.03883448,  0.02605217,
         0.00689759, -0.06503404,  0.00525253,  0.01287744,  0.02599726,
        -0.01666297, -0.03203052, -0.0140506 ,  0.05501854,  0.0406184 ,
         0.05119792,  0.0056717 , -0.02346437, -0.03816985,  0.01163796],
       dtype=float32),
 array([-0.03060074, -0.01253008, -0.05797678, -0.01393101,  0.00424226,
         0.0066396 , -0.02697883,  0.01528488,  0.08123344, -0.02655926,
         0.02522497, -0.05560829, -0.0155972 ,  0.09196401,  0.02334286,
        -0.12063598, -0.05654754, -0.08536929, -0.112646  ,  0.01996975],
       dtype=float32),
 array([ 0.03833615,  0.01111039,  0.00976846, -0.03

In [ ]:
mapper = get_mapper()
X_train, y_train, mapper = transform_df(train_clean, mapper, fit=True)
X_valid, y_valid, mapper = transform_df(valid_clean, mapper, fit=False)

[nltk_data] Downloading package stopwords to /Users/erika/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [10]:
# TODO: write to file